# Generated by Django 4.2 on 2023-04-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_patient', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(max_length=30)),
                ('symptom1', models.CharField(max_length=30)),
                ('symptom2', models.CharField(max_length=30)),
                ('symptom3', models.CharField(max_length=30)),
                ('symptom4', models.CharField(max_length=30)),
                ('symptom5', models.CharField(max_length=30)),
                ('symptom6', models.CharField(max_length=30)),
                ('symptom7', models.CharField(max_length=30)),
                ('symptom8', models.CharField(max_length=30)),
                ('symptom9', models.CharField(max_length=30)),
                ('symptom10', models.CharField(max_length=30)),
                ('symptom11', models.CharField(max_length=30)),
                ('symptom12', models.CharField(max_length=30)),
                ('symptom13', models.CharField(max_length=30)),
                ('symptom14', models.CharField(max_length=30)),
                ('symptom15', models.CharField(max_length=30)),
                ('symptom16', models.CharField(max_length=30)),
                ('symptom17', models.CharField(max_length=30)),
                ('symptom18', models.CharField(max_length=30)),
                ('symptom19', models.CharField(max_length=30)),
                ('symptom20', models.CharField(max_length=30)),
                ('symptom21', models.CharField(max_length=30)),
                ('symptom22', models.CharField(max_length=30)),
                ('symptom23', models.CharField(max_length=30)),
                ('symptom24', models.CharField(max_length=30)),
                ('symptom25', models.CharField(max_length=30)),
                ('symptom26', models.CharField(max_length=30)),
                ('symptom27', models.CharField(max_length=30))
            ],
        ),
    ]
